# WeaponMaster config


warnOnNoPaper: true

dragonDescent:
  enable: true

rng:
  coreStaff: 0.02
  leviathanHeart: 0.12
  silkyString: 0.001
  lifeCore: 0.008
  expertSeal: 0.025
  endArtifact: 0.09
  # Deepslate coal doesn't drop XP 1/3 of the time, so this is actually 8%, not 12%
  plutonium: 0.12
  diamondApex: 0.035
  emeraldApex: 0.12
  redstoneApex: 0.0075


# Weapon configs
# Customize weapon behavior here
# Changes to these values affect weapons that have already been crafted, but
# will not affect their item names/descriptions.


ares:
  damage: 2.0
artemis:
  seeking_distance: 3.8
assassinsblade:
  damage_multiplier: 1.4
atomBomb:
  disable: true
  enforceGlobalCooldown: false
bombcannon:
  explosion_power: 1.25
cavemansword:
  # Adjusts how fast XP is gained, default is 0.25
  multiplier: 0.25
deathScythe:
  damage_ratio: 0.3
  cooldownTicks: 10
  strength5Threshold: 16.0
  strength4Threshold: 11.0
  strength3Threshold: 7.0
  strength2Threshold: 3.0
dragonArmor:
  protection_each: 0.05
  protection_enchant: 0.0075
  attack_bonus_each: 0.02
  # When enchanted with huge protection levels, still take 2% damage by default
  min_damage_multiplier: 0.02
  reduction_hunger: 0.6666666666666666
  # Fixes hurt cam stuttering in lava or fire
  # This should be patched in later versions (should be fixed in 1.21.4 Paper) but if you're on an earlier version
  # or Spigot and experience stuttering, try setting this to true
  fixStuttering: false
dragonelytra:
  # When you are slower, you get bonus_max bonus; when you are faster, you get bonus_min bonus
  bonus_max: 0.01
  bonus_min: 0.005
  ender_eye_bonus: 7.5
dragonsword:
  # Bonuses follow a triangular distribution with minimum A, maximum B, mode C
  a: 0.0
  b: 0.8
  c: 0.25
  dragon_armor_buff: 1.25
endsword:
  teleport_distance: 7.0
excalibur:
  damage: 5.0
  cooldown_ticks: 120
exodus:
  cooldown_ticks: 80
fireball:
  velocity: 1.9
  power: 3.0
  seekingDistance: 3.0
  heatSeeking: false
guidedMissile:
  # Max distance that players can lock on to targets
  max_distance: 96.0
  # How much entity hitboxes are expanded
  ray_size: 2.9
  ticks_to_lock: 16
  # Target is lost if line of sight is lost for this many ticks in a row
  retain_target_ticks: 70
  block_explosion_power: 6.0
  entity_explosion_power: 19.0
  # If missile explodes without a target
  weak_explosion_power: 5.0
  proximity_distance: 6.5
  acceleration: 0.63
  air_resistance: 0.73
helios:
  # Radius of the fire ring on right click
  impact_distance: 5.0
  food_cost: 2.666666
  max_damage_level: 80
  max_damage_amount: 0.5
hermes:
  activate_chance: 0.12
  cooldown_ticks: 320
lifehelmet:
  cooldown_ticks: 12000
napalmMissile:
  explosive_power: 6.0
  fire_power: 14.0
ninjabow:
  cooldown_ticks: 8
pilot:
  damage_multiplier: 0.111111111111111
plutonium:
  damage: 70.0
  knockback_strength: 9.0
  crit_multiplier: 1.2
  cooldown_ticks: 400
poseidon:
  lightning_chance: 0.1
rocketStick:
  knockback_other: 10.0
  knockback_self: 8.3
  teleport_distance: 6.5
scorpionBow:
  duration: 120
  amplifier: 0
scylla:
  health_threshold: 8.0
  max_reduction: 0.35
shreddedAxe:
  survival_duration: 400
  zombie_max_hp: 50.0
  max_zombies: 10
sniper:
  cooldown_ticks: 30
throwingKnife:
  knife_speed: 0.5
  # How many ticks to throw forward
  # The total throw time is twice this (forward + back)
  ticks: 30
valkyrieAxe:
  food_cost: 2.666666
  # Spread damage is multiplied by this number
  damage_factor: 0.75
  firestorm_radius: 25.0
  # Size of the firestorm cone in degrees
  max_angle_deg: 32.0
  firestorm_knockback: 14.0
vampAxe:
  heal_multiplier: 0.16
witchSword:
  heal_factor: 0.15
witherStaff:
  chargedChance: 0.06
  cooldownTicks: 20
  cooldownTicksUpgraded: 4
  kingShieldAmount: 10.0
  # Half of the shield is converted into healing after this many ticks
  shieldDecayAfter: 200
  # How many ticks before the shield can be used again
  shieldCooldownTicks: 300
