# WeaponMaster config


warnOnNoPaper: true

dragonDescent:
  enable: true

rng:
  coreStaff: 0.02
  leviathanHeart: 0.12
  silkyString: 0.001
  lifeCore: 0.008
  expertSeal: 0.025
  endArtifact: 0.09
  # Deepslate coal doesn't drop XP 1/3 of the time, so this is actually 8%, not 12%
  plutonium: 0.12
  diamondApex: 0.035
  emeraldApex: 0.12
  redstoneApex: 0.0075


# Weapon configs
# Customize weapon behavior here
# Changes to these values affect weapons that have already been crafted, but
# will not affect their item names/descriptions.


ares:
  damage: 2.0
artemis:
  seeking_distance: 3.8
assassinsblade:
  damage_multiplier: 1.4
atomBomb:
  disable: true
  enforceGlobalCooldown: false
bombcannon:
  explosion_power: 1.25
cavemansword:
  # Adjusts how fast XP is gained, default is 0.25
  multiplier: 0.25
deathScythe:
  damage_ratio: 0.3
  cooldownTicks: 10
  strength5Threshold: 16.0
  strength4Threshold: 11.0
  strength3Threshold: 7.0
  strength2Threshold: 3.0
dragonArmor:
  protection_each: 0.05
  protection_enchant: 0.0075
  attack_bonus_each: 0.02
  # When enchanted with huge protection levels, still take 2% damage by default
  min_damage_multiplier: 0.02
  reduction_hunger: 0.6666666666666666
  # Fixes hurt cam stuttering in lava or fire
  # This should be patched in later versions (should be fixed in 1.21.4 Paper) but if you're on an earlier version
  # or Spigot and experience stuttering, try setting this to true
  fixStuttering: false
dragonelytra:
  # When you are slower, you get bonus_max bonus; when you are faster, you get bonus_min bonus
  bonus_max: 0.01
  bonus_min: 0.005
  ender_eye_bonus: 7.5
fireball:
  heatSeeking: false
witherStaff:
  chargedChance: 0.06
  cooldownTicks: 20
  cooldownTicksUpgraded: 4
