# WeaponMaster config


warnOnNoPaper: true

dragonDescent:
  enable: true

rng:
  coreStaff: 0.02
  leviathanHeart: 0.12
  silkyString: 0.001
  lifeCore: 0.008
  expertSeal: 0.025
  endArtifact: 0.09
  # Deepslate coal doesn't drop XP 1/3 of the time, so this is actually 8%, not 12%
  plutonium: 0.12
  diamondApex: 0.035
  emeraldApex: 0.12
  redstoneApex: 0.0075


# Weapon configs
# Customize weapon behavior here
# Changes to these values affect weapons that have already been crafted, but
# will not affect their item names/descriptions.


ares:
  damage: 2.0
atomBomb:
  disable: true
  enforceGlobalCooldown: false
deathScythe:
  cooldownTicks: 10
  strength5Threshold: 16.0
  strength4Threshold: 11.0
  strength3Threshold: 7.0
  strength2Threshold: 3.0
fireball:
  heatSeeking: false
witherStaff:
  chargedChance: 0.06
  cooldownTicks: 20
  cooldownTicksUpgraded: 4
dragonArmor:
  # Fixes hurt cam stuttering in lava or fire
  # This should be patched in later versions (should be fixed in 1.21.4 Paper) but if you're on an earlier version
  # or Spigot and experience stuttering, try setting this to true
  fixStuttering: false